spring.application.name=quipux
server.port=8080
# JWT
security.jwt.secret=level_security_QUIPUX_123456_password
security.jwt.expiration-minutes=60
# H2
spring.datasource.url=jdbc:h2:mem:quipuxdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sAdmin
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#spotify

spotify.client-id=aa8a9c6c089545e69785fb0002fe9aaa
spotify.client-secret=76b6b75c45884fa8a7fb5ac6ffca5381
spotify.accounts-base-url=https://accounts.spotify.com
spotify.api-base-url=https://api.spotify.com/v1
